name: pendulum-chaos-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.26.4
  - scipy>=1.13.1
  - pandas>=2.2.2
  - matplotlib>=3.9.0
  - sympy>=1.12
  - scikit-learn>=1.5.0
  - seaborn>=0.13.2
  - plotly>=5.22.0
  - tqdm>=4.66.4
  - ipywidgets>=8.1.2
  - notebook>=7.2.0
  - jupyterlab>=4.1.8
  - pip
  - pip:
      - nolds==0.5.2
      - nbstripout==0.6.1
      - black==24.4.2
      - flake8==7.0.0
      - isort==5.13.2
      - pylint==3.2.2
